[versions]
lombok = "1.18.34"
junit-jupiter = "5.10.3"

[libraries]

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
